import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Footer from "./components/Footer/Footer"
import Head from "./components/head/head"
import { Providers } from "./providers"
import ThemeSwitcher from "./components/head/ThemeButton/ThemeSwitcher"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Head />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
